archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
builds:
  - goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    dir: ./provider
    main: ./cmd/pulumi-resource-honeycomb
    binary: pulumi-resource-honeycomb
    ldflags:
      - -X github.com/MaterializeInc/pulumi-honeycomb/provider/pkg/version.Version={{.Version}}
changelog:
  skip: true
