archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
builds:
  - goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    env:
      - CGO_ENABLED=0
    dir: ./provider
    main: ./cmd/pulumi-resource-honeycomb
    binary: pulumi-resource-honeycomb
    ldflags:
      - -X github.com/MaterializeInc/pulumi-honeycomb/provider/pkg/version.Version={{.Version}}
      - -X github.com/honeycombio/terraform-provider-honeycombio/honeycombio.providerVersion=pulumi-honeycomb/{{.Version}}
changelog:
  skip: true
