// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "honeycomb:apiKey")
}
func GetApiUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "honeycomb:apiUrl")
}

// Enable the API client's debug logs. By default, a `TF_LOG` setting of debug or higher will enable this.
func GetDebug(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "honeycomb:debug")
}
